### ISSUE TITLE
COUNTING OBJECTS DETECTED

### ISSUE THREAD

**Issue by ebyau** [shayanalibhatti/Retail-Store-Item-Detection-using-YOLOv5#4]
How can i show the number of objects detected when training on a single object

**Comment by Keshav-Aggarwal** [comment]
Do you want the total number of objects detected or total number of object classes detected?

**Comment by ebyau** [comment]
i have only one class of objects to detect, i want to show the total number of objects detected

**Comment by Keshav-Aggarwal** [comment]
If you take the length of the returned object that will give you the total number of objects detected.
