### ISSUE TITLE
Downloading Training Set from Roboflow

### ISSUE THREAD

**Issue by jkassis** [shayanalibhatti/Retail-Store-Item-Detection-using-YOLOv5#5]
Little confused about this. What URL to use?

**Comment by shayanalibhatti** [comment]
Try this. This one works.

https://drive.google.com/u/0/uc?id=1iq93lCdhaPUN0fWbLieMtzfB1850pKwd&export=download

**Comment by jkassis** [comment]
pefect! thank you!

**Comment by RoyAmoyal** [comment]
@shayanalibhatti is the dataset on the link https://drive.google.com/u/0/uc?id=1iq93lCdhaPUN0fWbLieMtzfB1850pKwd&export=download is already annotated for yolov5 format?

**Comment by RoyAmoyal** [comment]
@shayan-NECX

**Comment by shayanalibhatti** [comment]
I dont remember, its been quite some time. Sorry.
